[project]
id = "gamalaser-aprovacao"
name = "Gama Laser - Aprovação de Design"
version = "1.0.0"

[[build.buildpacks]]
uri = "heroku-community/static"

[[build.env]]
name = "BP_STATIC_ENABLED"
value = "true"
