[project]
id = "gamalaser-aprovacao"
name = "Gama Laser - Aprovação de Design"
version = "1.0.0"

[[build.env]]
name = "APP_ROOT"
value = "."

[[build.buildpacks]]
uri = "paketo-buildpacks/nginx"

[[build.env]]
name = "BP_WEB_SERVER"
value = "nginx"

[[build.env]]
name = "BP_LAUNCHPOINT"
value = "index.html"
